# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "win7.box"

   config.vm.guest = :windows
   config.vm.communicator = :winrm
   config.winrm.username = "IEUser"
   config.winrm.password = "Passw0rd!" 

   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.customize ['modifyvm', :id, '--vram', '256']
     vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
     vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
     # Customize the amount of memory on the VM:
     vb.memory = "6024"
     vb.cpus = 2
   end




end
