forge 'http://forge.puppetlabs.com'

# Local modules
mod 'apache', :local =>true
mod 'php', :local =>true
mod 'mariadb', :local =>true

# Modules discovered by generate-puppetfile
mod 'puppet/staging', '3.2.0'
mod 'puppetlabs/mysql', '13.2.0'
mod 'puppetlabs/stdlib', '8.4.0'
