# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

 
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
   config.vm.box = "Microsoft/EdgeOnWindows10"
   config.vm.box_version = "1.0"

   config.vm.guest = :windows
   config.vm.communicator = :winrm
   config.winrm.username = "IEUser"
   config.winrm.password = "Passw0rd!"   
   #config.vm.network "forwarded_port", host: 33389, guest: 3389, id: "rdp", auto_correct: true  
  
   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.customize ['modifyvm', :id, '--vram', '256']
     # Customize the amount of memory on the VM:
     vb.memory = "6024"
     vb.cpus = 2
   end
 
end
