# -*- mode: ruby -*-
# vi: set ft=ruby :
# can be changed
BOX_IMAGE = 'ubuntu/xenial64'.freeze

Vagrant.configure('2') do |config|
  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vbguest.auto_update = true
    config.vbguest.no_remote = true
  end

  config.vm.define 'master', primary: true, autostart: true do |devbox|
    devbox.vm.hostname = 'fluntd-master'
    devbox.vm.box = BOX_IMAGE
    devbox.vm.network(:private_network, ip: '10.0.0.90')

    devbox.vm.provider :virtualbox do |conf|
      conf.gui = false
      conf.customize ['modifyvm', :id, '--vram', '10']
      conf.customize ['modifyvm', :id, '--usb', 'off']
      conf.name = 'log-aggregator'
      conf.cpus = 2
      conf.memory = 400
    end
  end

  config.vm.define 'node-agent', primary: true, autostart: true do |agent|
    agent.vm.hostname = 'fluentd-agent'
    agent.vm.box = BOX_IMAGE
    agent.vm.network(:private_network, ip: '10.0.0.23')

    agent.vm.provider :virtualbox do |conf|
      conf.gui = false
      conf.customize ['modifyvm', :id, '--vram', '10']
      conf.customize ['modifyvm', :id, '--usb', 'off']
      conf.name = 'log-forwarder'
      conf.cpus = 2
      conf.memory = 400
    end
  end
end
