# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = 'minimal/xenial64'

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vbguest.auto_update = false
    config.vbguest.no_remote = false
  end

  config.vm.define 'master', primary: true, autostart: true do |devbox|
    devbox.vm.hostname = 'master-devbox'
    devbox.vm.box = BOX_IMAGE
    devbox.vm.network(:private_network, ip: '10.0.0.90')

    devbox.vm.provider :virtualbox do |conf|
      conf.gui = false
      conf.customize ['modifyvm', :id, '--usb', 'off']
      conf.name = 'dev-master'
      conf.cpus = 1
      conf.memory = 400
    end
    # update and upgrade software packages
    devbox.vm.provision 'shell', path: 'provision/provision.update.sh', privileged: false
    # # install ansible
    devbox.vm.provision 'shell', path: 'provision/provision.pip.sh', privileged: false
    devbox.vm.provision 'shell', path: 'provision/provision.ansible.sh', privileged: false
    # # install awscli, elb and boto3
    devbox.vm.provision 'shell', path: 'provision/provision.awscli.sh', privileged: false
    devbox.vm.provision 'shell', path: 'provision/provision.docker.sh', privileged: false
    # # move keys and write to config and authorized_keys
    devbox.vm.provision 'shell', path: 'provision/provision.ssh.sh', privileged: false
    # provision fly for concourse
    devbox.vm.provision 'shell', path: 'provision/provision.fly.sh', privileged: false
    # # clear the box
    devbox.vm.provision 'shell', path: 'provision/provision.cleaner.sh', privileged: false
  end
end
