name: auto merge dependency updates

on:
  - pull_request
  - pull_request_review
  - pull_request_target

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Merge dependency updates
        uses: tjenkinson/gh-action-auto-merge-dependency-updates@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-actors: dependabot-preview[bot], dependabot[bot], renovate[bot]
