name: auto-merge-dependencies

on:
  pull_request_target:
    types: [labeled]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    # Specifically check that dependabot (or another trusted party) created this pull-request, and that it has been labelled correctly.
    if: >
      github.event.pull_request.user.login == 'dependabot[bot]' ||
        github.event.pull_request.user.login == 'dependabot-preview[bot]' ||
        github.event.pull_request.user.login == 'renovate[bot]'
    steps:
    - name: identify actor & creator
      run: |
        echo "actor: ${{ github.actor }}"
        echo "creator: ${{ github.event.pull_request.user.login }}"
    # Specifically check the creator of the pull-request, not the actor.
    - id: auto-merge-bot
      uses: alexwilson/enable-github-automerge-action@1.1.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
